//─────────────────────────────────────────────────────────────────────────────────────────────────┐
/**
 * @file          generators/tmtools-tm1-transform.ts
 * @copyright     Vivek M. Chawla - 2018
 * @author        Vivek M. Chawla <@VivekMChawla>
 * @summary       Yeoman Generator for transforming TM1 metadata and data into a TM2-ready bundle.
 * @description   Salesforce CLI Plugin command (tmtools:tm1:transform) that allows a Salesforce
 *                Administrator to transform previously extracted Territory Management (TM1)
 *                metadata and data into a format that is ready to be deployed to the org the data
 *                was extracted from once it's converted to TM2.
 * @version       1.0.0
 * @license       MIT
 */
//─────────────────────────────────────────────────────────────────────────────────────────────────┘
// Import External Libraries & Modules
import chalk      from  'chalk';  // Helps write colored text to the console.
import * as path  from  'path';   // Library. Helps resolve local paths at runtime.

// Import Internal Libraries
import * as iq                          from  '../modules/sfdx-falcon-util/interview-questions';  // Library. Helper functions that create Interview Questions.
import * as listrTasks                  from  '../modules/sfdx-falcon-util/listr-tasks';          // Library. Helper functions that make using Listr with SFDX-Falcon easier.

// Import Internal Classes & Functions
import {SfdxFalconDebug}                from  '../modules/sfdx-falcon-debug';                     // Class. Provides custom "debugging" services (ie. debug-style info to console.log()).
import {SfdxFalconError}                from  '../modules/sfdx-falcon-error';                     // Class. Extends SfdxError to provide specialized error structures for SFDX-Falcon modules.
import {SfdxFalconInterview}            from  '../modules/sfdx-falcon-interview';                 // Class. Provides a standard way of building a multi-group Interview to collect user input.
import {SfdxFalconResult}               from  '../modules/sfdx-falcon-result';                    // Class. Framework for creating results-driven, informational objects with a concept of heredity (child results).
import {SfdxFalconKeyValueTableDataRow} from  '../modules/sfdx-falcon-util/ux';                   // Interface. Represents a row of data in an SFDX-Falcon data table.
import {SfdxFalconTableData}            from  '../modules/sfdx-falcon-util/ux';                   // Interface. Represents and array of SfdxFalconKeyValueTableDataRow objects.
import {GeneratorOptions}               from  '../modules/sfdx-falcon-yeoman-command';            // Interface. Represents options used by SFDX-Falcon Yeoman generators.
import {SfdxFalconYeomanGenerator}      from  '../modules/sfdx-falcon-yeoman-generator';          // Class. Abstract base class class for building Yeoman Generators for SFDX-Falcon commands.
//import {TmToolsTransform}               from  '../modules/tm-tools-transform';                    // Class. Provides TM1 to TM2 transformation services given the location of source config.

// Import TM-Tools Types
//import {TM1AnalysisReport}              from  '../modules/tm-tools-types';                        // Interface. Represents the data that is generated by a TM1 Analysis Report.
import {TM1ExtractionReport}            from  '../modules/tm-tools-types';                        // Interface. Represents the data that is generated by a TM1 Extraction Report.

// Requires
const yosay = require('yosay');   // ASCII art creator brings Yeoman to life.

// Set the File Local Debug Namespace
const dbgNs = 'GENERATOR:tmtools-tm1-transform:';
SfdxFalconDebug.msg(`${dbgNs}`, `Debugging initialized for ${dbgNs}`);


//─────────────────────────────────────────────────────────────────────────────────────────────────┐
/**
 * @interface   InterviewAnswers
 * @description Represents answers to the questions asked in the Yeoman interview.
 */
//─────────────────────────────────────────────────────────────────────────────────────────────────┘
interface InterviewAnswers {
  extractionDirectory:  string;
}

//─────────────────────────────────────────────────────────────────────────────────────────────────┐
/**
 * @class       Tm1Transform
 * @extends     SfdxFalconYeomanGenerator
 * @summary     Yeoman generator class. Transforms local TM1 configuration (data+metadata) files.
 * @description Uses Yeoman to run through an interview, then transforms TM1 configuration based on
 *              the specifications found in the user's tm1-extraction.json file.
 * @public
 */
//─────────────────────────────────────────────────────────────────────────────────────────────────┘
export default class Tm1Transform extends SfdxFalconYeomanGenerator<InterviewAnswers> {

  // Define class members specific to this Generator.
  protected extractedDataDir:           string;               // Fully qualified path to location where extracted source DATA (ie. CSV files) are already stored.
  protected extractedMetadataDir:       string;               // Fully qualified path to location where extracted source METADATA (ie. package manifest and other XML) are already stored.
  protected intermediateFilesDir:       string;               // Fully qualified path to location where "intermediate" files will be stored. These files are either partially transformed, or will support later steps in the process.
  protected tm1ExtractionFilePath:      string;               // Complete path to the tm1-extraction.json file that will be created
  protected tm1ExtractionReport:        TM1ExtractionReport;  // Report data created by a previously executed TM1 Extraction.
  //protected tm1Transform:               TmToolsTransform;     // Provides TM1 to TM2 transformation services given the location of source config.
  protected tm1TransformationFilePath:  string;               // ???
  protected transformedMetadataDir:     string;               // Fully qualified path to location where transformed METADATA (ie. package manifest and other XML) will be stored.
  protected transformedDataDir:         string;               // Fully qualified path to location where transformed DATA (ie. CSV files) will be stored.

  //───────────────────────────────────────────────────────────────────────────┐
  /**
   * @constructs  Tm1Transform
   * @param       {string|string[]} args Required. Not used (as far as I know).
   * @param       {GeneratorOptions}  opts Required. Sets generator options.
   * @description Constructs a Tm1Transform object.
   * @public
   */
  //───────────────────────────────────────────────────────────────────────────┘
  constructor(args:string|string[], opts:GeneratorOptions) {

    // Call the parent constructor to initialize the Yeoman Generator.
    super(args, opts);

    // Initialize the "Confirmation Question".
    this.confirmationQuestion = 'Transform TM1 configuration (data/metadata) to TM2 using the above settings?';

    // Initialize extract and transform directory variables.
    this.extractedDataDir           = '';
    this.extractedMetadataDir       = '';
    this.intermediateFilesDir       = '';
    this.tm1ExtractionFilePath      = '';
    this.tm1ExtractionReport        = null;
//    this.tm1Transform               = null;
    this.tm1TransformationFilePath  = '';
    this.transformedMetadataDir     = '';
    this.transformedDataDir         = '';

    // Initialize DEFAULT Interview Answers.
    this.defaultAnswers.extractionDirectory = path.resolve(opts.sourceDir as string);

    // Initialize Shared Data.
    this.sharedData['cliCommandName']       = this.cliCommandName;  // ???
    this.sharedData['tm1ExtractionReport']  = {};                   // ???
  }

  //───────────────────────────────────────────────────────────────────────────┐
  /**
   * @method      _buildInterview
   * @returns     {SfdxFalconInterview<InterviewAnswers>} Returns a fully fleshed
   *              SfdxFalconInterview object with zero or more prompts that the
   *              user will answer in an interview once this is run.
   * @description Allows the developer to build a complex, multi-step interview
   *              that Yeoman will execute during the "prompting" phase.
   * @protected
   */
  //───────────────────────────────────────────────────────────────────────────┘
  protected _buildInterview():SfdxFalconInterview<InterviewAnswers> {

    // Initialize the Interview object.
    const interview = new SfdxFalconInterview<InterviewAnswers>({
      defaultAnswers:     this.defaultAnswers,
      confirmation:       iq.confirmProceedRestart,
      confirmationHeader: chalk.yellow('Review Your Settings:'),
      display:            this._buildInterviewAnswersTableData,
      context:            this,
      sharedData:         this.sharedData
    });

    // Group 0: Specify the directory containing the TM1 config extraction.
    interview.createGroup({
      title:        chalk.yellow('\nTM1 Extraction Directory:'),
      questions:    iq.provideTm1ExtractionDirectory
    });

    // Finished building the Interview.
    return interview;
  }

  //───────────────────────────────────────────────────────────────────────────┐
  /**
   * @method      _buildInterviewAnswersTableData
   * @param       {InterviewAnswers}  userAnswers Required.
   * @returns     {Promise<SfdxFalconTableData>}
   * @description Builds an SfdxFalconTableData object based on the Interview
   *              Answer values provided by the caller. This function can be
   *              used by an SfdxFalconInterview to reflect input to the user
   *              at the end of an Interview.
   * @protected @async
   */
  //───────────────────────────────────────────────────────────────────────────┘
  protected async _buildInterviewAnswersTableData(interviewAnswers:InterviewAnswers):Promise<SfdxFalconTableData> {

    // Declare an array of Falcon Table Data Rows
    const tableData = new Array<SfdxFalconKeyValueTableDataRow>();

    // Grab the TM1 Extraction Report from Shared Data, then extract the key Org Info and Record Count info from it.
    const tm1ExtractionReport       = this.sharedData['tm1ExtractionReport'] as TM1ExtractionReport;
    const orgId                     = tm1ExtractionReport.orgInfo.orgId;
    const username                  = tm1ExtractionReport.orgInfo.username;
    const loginUrl                  = tm1ExtractionReport.orgInfo.loginUrl;
    const createdOrgInstance        = tm1ExtractionReport.orgInfo.createdOrgInstance;
    const territoryRecordCount      = tm1ExtractionReport.actualTm1RecordCounts.territoryRecordCount;
    const userTerritoryRecordCount  = tm1ExtractionReport.actualTm1RecordCounts.userTerritoryRecordCount;
    const ataRuleRecordCount        = tm1ExtractionReport.actualTm1RecordCounts.ataRuleRecordCount;
    const ataRuleItemRecordCount    = tm1ExtractionReport.actualTm1RecordCounts.ataRuleItemRecordCount;
    const accountShareRecordCount   = tm1ExtractionReport.actualTm1RecordCounts.accountShareRecordCount;

    // User-supplied answer.
    tableData.push({option:'TM1 Extraction Directory:', value:`${interviewAnswers.extractionDirectory}`});

    // Answers read from the specified tm1-extraction.json file.
    tableData.push({option:'Username:',                   value:`${username}`});
    tableData.push({option:'Org ID:',                     value:`${orgId}`});
    tableData.push({option:'Login Url:',                  value:`${loginUrl}`});
    tableData.push({option:'Org Instance:',               value:`${createdOrgInstance}`});
    tableData.push({option:'Territories:',                value:`${territoryRecordCount}`});
    tableData.push({option:'User/Territory Assignments:', value:`${userTerritoryRecordCount}`});
    tableData.push({option:'Assignment Rules:',           value:`${ataRuleRecordCount}`});
    tableData.push({option:'Assignment Rule Items:',      value:`${ataRuleItemRecordCount}`});
    tableData.push({option:'Account Shares:',             value:`${accountShareRecordCount}`});

    // Return the Falcon Table Data.
    return tableData;
  }

  //───────────────────────────────────────────────────────────────────────────┐
  /**
   * @method      _transformTm1Config
   * @returns     {Promise<void>}
   * @description Uses information from the User's "Final Answers" to transform
   *              a set of local TM1 Config (data and metadata) into a suite of
   *              files that can be used to deploy/load TM2 Config back into the
   *              original source org once Enterprise Territory Management (TM2)
   *              has been activated.
   * @protected @async
   */
  //───────────────────────────────────────────────────────────────────────────┘
  protected async _transformTm1Config():Promise<void> {

    // Define Listr Tasks for executing the transformation.
    const tm1DataTransformation =
      listrTasks.tm1DataTransform.call(this,
                                       this.tm1ExtractionReport,
                                       this.extractedMetadataDir,
                                       this.extractedDataDir,
                                       this.transformedMetadataDir,
                                       this.transformedDataDir,
                                       this.intermediateFilesDir);

    // Show a message to the User letting them know we're going to start these tasks.
    console.log(chalk`{yellow Transforming TM1 Data/Metadata to TM2...}`);
    
    // Run the "Fetch and Convert Package" tasks. Make sure to use await since Listr will run asynchronously.
    const tm1TransformationResults = await tm1DataTransformation.run()
      .catch(utilityResult => {

        // DEBUG
        SfdxFalconDebug.obj(`${dbgNs}writing:utilityResult:`, utilityResult);

        // If we get an Error, just throw it.
        if (utilityResult instanceof Error) {
          throw utilityResult;
        }

        // If we get an SfdxFalconResult, link its Error Object to a new SfdxFalconError and throw it.
        if (utilityResult instanceof SfdxFalconResult) {
          throw new SfdxFalconError( `Transformation of TM1 data/metadata failed.`
                                   , `Tm1TransformationError`
                                   , `${dbgNs}writing`
                                   , utilityResult.errObj);
        }

        // If we get here, who knows what we got. Wrap it as an SfdxFalconError and throw it.
        throw SfdxFalconError.wrap(utilityResult);
      });

    // DEBUG
    SfdxFalconDebug.obj(`${dbgNs}writing:tm1TransformationResults:`, tm1TransformationResults);

    // Add a success message
    this.generatorStatus.addMessage({
      type:     'success',
      title:    `Transform TM1 Config`,
      message:  `Success - TM1 configuration (data/metadata) successfully transformed to TM2`
    });

    // Add a line break to separate the output of this section from others
    console.log('');

    // Done with TM1 Transformation.
    return;
  }

  //───────────────────────────────────────────────────────────────────────────┐
  /**
   * @method      initializing
   * @returns     {Promise<void>}
   * @description STEP ONE in the Yeoman run-loop.  Uses Yeoman's "initializing"
   *              run-loop priority.
   * @protected @async
   */
  //───────────────────────────────────────────────────────────────────────────┘
  protected async initializing():Promise<void> {

    // Show the Yeoman to announce that the generator is running.
    this.log(yosay(this.openingMessage));
  }

  //───────────────────────────────────────────────────────────────────────────┐
  /**
   * @method      prompting
   * @returns     {Promise<void>}
   * @description STEP TWO in the Yeoman run-loop. Interviews the User to get
   *              information needed by the "writing" and "installing" phases.
   * @protected @async
   */
  //───────────────────────────────────────────────────────────────────────────┘
  protected async prompting():Promise<void> {

    // Let the User know that the Interview is starting.
    console.log(chalk`{yellow Starting TM1 transformation interview...}`);

    // Call the default prompting() function. Replace with custom behavior if desired.
    return this._default_prompting();
  }

  //───────────────────────────────────────────────────────────────────────────┐
  /**
   * @method      configuring
   * @returns     {Promise<void>}
   * @description STEP THREE in the Yeoman run-loop. Perform any pre-install
   *              configuration steps based on the answers provided by the User.
   * @protected @async
   */
  //───────────────────────────────────────────────────────────────────────────┘
  protected async configuring():Promise<void> {

    // Call the default configuring() function. Replace with custom behavior if desired.
    return this._default_configuring();
  }

  //───────────────────────────────────────────────────────────────────────────┐
  /**
   * @method      writing
   * @returns     {Promise<void>}
   * @description STEP FOUR in the Yeoman run-loop. Typically, this is where
   *              you perform filesystem writes, git clone operations, etc.
   * @protected @async
   */
  //───────────────────────────────────────────────────────────────────────────┘
  protected async writing():Promise<void> {

    // Check if we need to abort the Yeoman interview/installation process.
    if (this.generatorStatus.aborted) {
      SfdxFalconDebug.msg(`${dbgNs}writing:`, `generatorStatus.aborted found as TRUE inside writing()`);
      return;
    }

    // Define paths for all Source and Target directories.
    this.extractedDataDir           = path.join(this.finalAnswers.extractionDirectory,  'tm1-extraction',     'extracted-data');
    this.extractedMetadataDir       = path.join(this.finalAnswers.extractionDirectory,  'tm1-extraction',     'extracted-metadata');
    this.intermediateFilesDir       = path.join(this.finalAnswers.extractionDirectory,  'tm1-transformation', 'intermediate-files');
    this.transformedDataDir         = path.join(this.finalAnswers.extractionDirectory,  'tm1-transformation', 'transformed-data');
    this.transformedMetadataDir     = path.join(this.finalAnswers.extractionDirectory,  'tm1-transformation', 'transformed-metadata');

    // Define paths to the Extraction Report (existing) and the Transformation Report (to be created).
    this.tm1ExtractionFilePath      = path.join(this.finalAnswers.extractionDirectory,  'tm1-extraction.json');
    this.tm1TransformationFilePath  = path.join(this.finalAnswers.extractionDirectory,  'tm1-transformation.json');

    // Save the TM1 Extraction Report that surfaced during the interview to a member variable.
    this.tm1ExtractionReport = this.sharedData['tm1ExtractionReport'] as TM1ExtractionReport;

    // Transform the user's TM1 config.
    await this._transformTm1Config();

    // Done with writing()
    return;
  }

  //───────────────────────────────────────────────────────────────────────────┐
  /**
   * @method      install
   * @returns     {void}
   * @description STEP FIVE in the Yeoman run-loop. Typically, this is where
   *              you perform operations that must happen AFTER files are
   *              written to disk. For example, if the "writing" step downloaded
   *              an app to install, the "install" step would run the
   *              installation.
   * @protected @async
   */
  //───────────────────────────────────────────────────────────────────────────┘
  protected async install() {

    // Call the default install() function. Replace with custom behavior if desired.
    return this._default_install();
  }

  //───────────────────────────────────────────────────────────────────────────┐
  /**
   * @method      end
   * @returns     {Promise<void>}
   * @description STEP SIX in the Yeoman run-loop. This is the FINAL step that
   *              Yeoman runs and it gives us a chance to do any post-Yeoman
   *              updates and/or cleanup.
   * @protected @async
   */
  //───────────────────────────────────────────────────────────────────────────┘
  protected async end():Promise<void> {

    // Call the default end() function. Replace with custom behavior if desired.
    return this._default_end();
  }
}
